[window]
decorations = "none"
opacity = 0.5
blur = true
padding = { x = 6, y = 6 }

[font]
#normal = { family = "VictorMono Nerd Font", style = "Regular" }
normal = { family = "Victor Mono", style = "Regular" }
bold = { family = "Victor Mono", style = "Bold" }
italic = { family = "Victor Mono", style = "Italic" } # Ensure this points to the italic variant
bold_italic = { family = "Victor Mono", style = "Bold Italic" }
size = 10.0
offset = { x = 0, y = 0 }

[colors.primary]
background = "#2b2b2b"
foreground = "#f5f5dc"
